services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    container_name: mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=demand_forecaster
      - MODEL_STAGE=Production
    depends_on:
      - mlflow

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  mlflow_data:
  grafana_data: